SAMPLE_COMPANIES = [
    {
        "id": 1,
        "url": "https://stripe.com",
        "domain": "stripe.com",
        "title": "Stripe | Payment Processing Platform for the Internet",
        "meta": "Stripe is a suite of APIs powering online payment processing and commerce solutions for internet businesses of all sizes.",
        "emails": ["support@stripe.com"],
        "phones": [],
        "domain_age": 15,
        "keywords_found": ["platform", "api", "enterprise", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/stripe",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 95,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=100&h=100&fit=crop"
    },
    {
        "id": 2,
        "url": "https://slack.com",
        "domain": "slack.com",
        "title": "Slack: Where Work Happens",
        "meta": "Slack brings team communication and collaboration into one place so you can get more work done.",
        "emails": ["feedback@slack.com"],
        "phones": [],
        "domain_age": 12,
        "keywords_found": ["platform", "enterprise", "automation"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/slack",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 92,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=100&h=100&fit=crop"
    },
    {
        "id": 3,
        "url": "https://notion.so",
        "domain": "notion.so",
        "title": "Notion – The all-in-one workspace",
        "meta": "A new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.",
        "emails": ["team@makenotion.com"],
        "phones": [],
        "domain_age": 8,
        "keywords_found": ["platform", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/notionhq",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 88,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?w=100&h=100&fit=crop"
    },
    {
        "id": 4,
        "url": "https://airtable.com",
        "domain": "airtable.com",
        "title": "Airtable | Everyone's app platform",
        "meta": "Airtable is a low-code platform for building collaborative apps.",
        "emails": ["support@airtable.com"],
        "phones": [],
        "domain_age": 10,
        "keywords_found": ["platform", "enterprise", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/airtable",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 90,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&h=100&fit=crop"
    },
    {
        "id": 5,
        "url": "https://figma.com",
        "domain": "figma.com",
        "title": "Figma: the collaborative interface design tool",
        "meta": "Figma connects everyone in the design process so teams can deliver better products, faster.",
        "emails": ["hello@figma.com"],
        "phones": [],
        "domain_age": 9,
        "keywords_found": ["platform", "enterprise"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/figma",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 89,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=100&h=100&fit=crop"
    },
    {
        "id": 6,
        "url": "https://hubspot.com",
        "domain": "hubspot.com",
        "title": "HubSpot | Inbound Marketing, Sales, and Service Software",
        "meta": "HubSpot offers a full platform of marketing, sales, customer service, and CRM software.",
        "emails": ["info@hubspot.com"],
        "phones": ["+1-888-482-7768"],
        "domain_age": 18,
        "keywords_found": ["crm", "saas", "platform", "enterprise"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/hubspot",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 100,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&h=100&fit=crop"
    },
    {
        "id": 7,
        "url": "https://salesforce.com",
        "domain": "salesforce.com",
        "title": "Salesforce: The Customer Success Platform",
        "meta": "Salesforce is the world's #1 CRM platform that employees can access entirely over the Internet.",
        "emails": ["info@salesforce.com"],
        "phones": ["+1-800-667-6389"],
        "domain_age": 25,
        "keywords_found": ["crm", "platform", "enterprise", "cloud"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/salesforce",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 100,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&h=100&fit=crop"
    },
    {
        "id": 8,
        "url": "https://zoom.us",
        "domain": "zoom.us",
        "title": "Zoom - One Platform to Connect",
        "meta": "Zoom's secure, reliable video platform powers all of your communication needs.",
        "emails": ["support@zoom.us"],
        "phones": ["+1-888-799-9666"],
        "domain_age": 13,
        "keywords_found": ["platform", "enterprise", "cloud"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/zoom-video-communications",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 97,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=100&h=100&fit=crop"
    },
    {
        "id": 9,
        "url": "https://shopify.com",
        "domain": "shopify.com",
        "title": "Shopify - Ecommerce Platform",
        "meta": "Shopify is an ecommerce platform that enables anyone to start, grow, and manage a business.",
        "emails": ["support@shopify.com"],
        "phones": ["+1-888-746-7439"],
        "domain_age": 19,
        "keywords_found": ["platform", "ecommerce", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/shopify",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 98,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1557821552-17105176677c?w=100&h=100&fit=crop"
    },
    {
        "id": 10,
        "url": "https://atlassian.com",
        "domain": "atlassian.com",
        "title": "Atlassian | Software Development and Collaboration Tools",
        "meta": "Millions of users globally rely on Atlassian products every day for improving software development, project management, collaboration, and code quality.",
        "emails": ["support@atlassian.com"],
        "phones": [],
        "domain_age": 22,
        "keywords_found": ["software", "platform", "enterprise", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/atlassian",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 95,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1551434678-e076c223a692?w=100&h=100&fit=crop"
    },
    {
        "id": 11,
        "url": "https://asana.com",
        "domain": "asana.com",
        "title": "Asana • Work Management Platform",
        "meta": "From the small stuff to the big picture, Asana organizes work so teams are clear what to do, why it matters.",
        "emails": ["hello@asana.com"],
        "phones": [],
        "domain_age": 15,
        "keywords_found": ["platform", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/asana",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 86,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop"
    },
    {
        "id": 12,
        "url": "https://monday.com",
        "domain": "monday.com",
        "title": "monday.com: Work OS for Teams",
        "meta": "A new way of working. monday.com Work OS is an open platform where anyone can create the tools they need to run every aspect of their work.",
        "emails": ["support@monday.com"],
        "phones": [],
        "domain_age": 10,
        "keywords_found": ["platform", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/mondaydotcom",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 87,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=100&h=100&fit=crop"
    },
    {
        "id": 13,
        "url": "https://mailchimp.com",
        "domain": "mailchimp.com",
        "title": "Mailchimp - Marketing, Automation & Email Platform",
        "meta": "Mailchimp helps small businesses do big things, with the right tools and guidance every step of the way.",
        "emails": ["support@mailchimp.com"],
        "phones": [],
        "domain_age": 22,
        "keywords_found": ["platform", "automation", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/mailchimp",
        "company_type": "B2B",
        "growth_level": "Medium",
        "has_careers_page": True,
        "score": 84,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=100&h=100&fit=crop"
    },
    {
        "id": 14,
        "url": "https://dropbox.com",
        "domain": "dropbox.com",
        "title": "Dropbox - Cloud Storage & File Sharing",
        "meta": "Dropbox brings everything—traditional files, cloud content, and web shortcuts—together in one place.",
        "emails": ["support@dropbox.com"],
        "phones": [],
        "domain_age": 17,
        "keywords_found": ["cloud", "platform"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/dropbox",
        "company_type": "B2B",
        "growth_level": "Medium",
        "has_careers_page": True,
        "score": 82,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=100&h=100&fit=crop"
    },
    {
        "id": 15,
        "url": "https://intercom.com",
        "domain": "intercom.com",
        "title": "Intercom | The Engagement OS",
        "meta": "Intercom is the only complete Customer Service solution that provides a seamless customer experience.",
        "emails": ["support@intercom.com"],
        "phones": [],
        "domain_age": 13,
        "keywords_found": ["platform", "solution", "service"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/intercom",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 88,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=100&h=100&fit=crop"
    },
    {
        "id": 16,
        "url": "https://zendesk.com",
        "domain": "zendesk.com",
        "title": "Zendesk - Customer Service Software & Support Ticket System",
        "meta": "Zendesk delivers better customer service with AI, automation, and unified customer data.",
        "emails": ["support@zendesk.com"],
        "phones": ["+1-888-670-4887"],
        "domain_age": 17,
        "keywords_found": ["software", "service", "enterprise"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/zendesk",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 93,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1556155092-8707de31f9c4?w=100&h=100&fit=crop"
    },
    {
        "id": 17,
        "url": "https://twilio.com",
        "domain": "twilio.com",
        "title": "Twilio - Communication APIs for SMS, Voice, Video & Authentication",
        "meta": "Twilio provides a cloud communications platform as a service enabling businesses to build, scale and operate communications within their software.",
        "emails": ["help@twilio.com"],
        "phones": ["+1-888-745-3000"],
        "domain_age": 16,
        "keywords_found": ["api", "platform", "cloud", "service"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/twilio-inc-",
        "company_type": "B2B",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 96,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=100&h=100&fit=crop"
    },
    {
        "id": 18,
        "url": "https://docusign.com",
        "domain": "docusign.com",
        "title": "DocuSign - Electronic Signature & Agreement Cloud",
        "meta": "DocuSign helps organizations connect and automate how they prepare, sign, act on, and manage agreements.",
        "emails": ["support@docusign.com"],
        "phones": ["+1-877-720-2040"],
        "domain_age": 21,
        "keywords_found": ["cloud", "enterprise", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/docusign",
        "company_type": "B2B",
        "growth_level": "Medium",
        "has_careers_page": True,
        "score": 91,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=100&h=100&fit=crop"
    },
    {
        "id": 19,
        "url": "https://squarespace.com",
        "domain": "squarespace.com",
        "title": "Squarespace - Website Builder",
        "meta": "Squarespace is the all-in-one platform to build a beautiful website and grow your business online.",
        "emails": ["customercare@squarespace.com"],
        "phones": [],
        "domain_age": 20,
        "keywords_found": ["platform", "solution"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/squarespace",
        "company_type": "B2C",
        "growth_level": "Medium",
        "has_careers_page": True,
        "score": 78,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=100&h=100&fit=crop"
    },
    {
        "id": 20,
        "url": "https://canva.com",
        "domain": "canva.com",
        "title": "Canva - Online Design and Visual Communication",
        "meta": "Canva is a free-to-use online graphic design tool. Use it to create social media posts, presentations, posters, videos, logos and more.",
        "emails": ["support@canva.com"],
        "phones": [],
        "domain_age": 11,
        "keywords_found": ["platform"],
        "has_contact": True,
        "linkedin": "https://linkedin.com/company/canva",
        "company_type": "B2C",
        "growth_level": "High",
        "has_careers_page": True,
        "score": 75,
        "score_color": "high",
        "logo_url": "https://images.unsplash.com/photo-1561070791-36c11767b26a?w=100&h=100&fit=crop"
    }
]
